# Site settings
title: unspecified
email: me@csell.net
description: |
  Sharing the passion...  
  Tech * Fabrication * BBQ   
  Website being launched soon. -Clark
owner: Clark Sell
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://unspecified.io" # the base hostname & protocol for your site

social:
  twitter: https://twitter.com/csell5
  github: https://github.com/csell5
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:

twitter_username: csell5
github_username:  csell5

# Build settings
markdown: kramdown
