# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: unspecified
email: me@csell.net
description: |
  asdf
  adsf 2
  Enjoy, Clark
owner: Clark Sell
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://unspecified.io" # the base hostname & protocol for your site

social:
  twitter: https://twitter.com/csell5
  github: https://github.com/csell5
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:

twitter_username: csell5
github_username:  csell5

# Build settings
markdown: kramdown
