# Site settings
title: Clark Sell's Unspecified
email: hello@unspecified.io
description: Software & Fabrication CO
owner: Clark Sell
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://unspecified.io" # the base hostname & protocol for your site
image: "/images/banner.jpg"

social:
  github: https://github.com/csell5
  twitter: https://twitter.com/csell5
  youtube-play: https://www.youtube.com/channel/UC5GVZFxKYul4cfsfhVAJGIA
  linkedin-square: https://linkedin.com/in/clarksell
  instagram: https://www.instagram.com/clarksell
  #facebook-official: https://facebook.com/<username>
  snapchat-ghost: http://snapchat.com/add/user/csell5
  medium: https://medium.com/@clarksell
  email: /contact

twitter_username: csell5
github_username:  csell5


# Build settings
markdown: kramdown
